### ISSUE TITLE
[Bug]: Avatar created with a totally different font

### ISSUE THREAD

**Issue by wq9578** [Voltra/filament-svg-avatar#1]
### What happened?

An avatar created with a totally different font appears.
While the panel uses the default font (_Inter_, a [sans-serif](https://en.wikipedia.org/wiki/Sans-serif) font), the avatar uses a font with [serifs](https://en.wikipedia.org/wiki/Serif).
See image attached: to the left the correct font, to the right the font with serifs.
![Avatar](https://github.com/Voltra/filament-svg-avatar/assets/121522862/a4d5d8be-23ed-4aea-8af8-47ccb658f0a7)

### How to reproduce the bug

```
composer require voltra/filament-svg-avatar
```

Add the following to class `AdminPanelProvider`:
```
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->defaultAvatarProvider(SvgAvatarsProviders::class)
```

### Package Version

1.0.1

### PHP Version

8.3.1

### Laravel Version

10.39.0

### Which operating systems does with happen with?

macOS

**Comment by Voltra** [comment]
Currently the avatar provider relies on the `font()` method of the panel (which I might as failed to document). I'll check things out to see if the svg can properly inherit the font from the body/html tag

**Comment by Voltra** [comment]
That also stems from the fact that the default avatar component uses an image tag, so there's no way to actually inherit the font unlike using an inline svg

**Comment by wq9578** [comment]
I'm not familiar enough with the matter to fully understand your comments.
Please let me know if I am supposed to do anything.
The log command `Log::info(filament()->getCurrentPanel()->getFontFamily());` yields the [Filament default font](https://filamentphp.com/docs/3.x/panels/themes#changing-the-font) _Inter_ (`[2024-01-21 16:19:01] local.INFO: Inter`), which is a sans-serif font: https://fonts.bunny.net/family/inter

**Comment by Voltra** [comment]
It should use that font, I'm wondering if the generated SVG (as it's an `<img/>` and not an `<svg>`) doesn't use the system's fonts instead of front-end loaded fonts.

I'm working on a release with more features, I'll probably add a blade/livewire component to help replace the original avatar one if need be.

**Comment by wq9578** [comment]
> I'm working on a release with more features, I'll probably add a blade/livewire component to help replace the original avatar one if need be.

How about implementing specifying the font manually in some config file?

**Comment by Voltra** [comment]
That's a good idea, I'll add that as well. For now it does take the font from the currently loaded panel.

**Comment by Voltra** [comment]
Hi there with the release of v1.1.0, can you check if everything works for you using the config file? I also have a mini guide in the README to replace filament's avatar component with an SVG one

**Comment by wq9578** [comment]
Still doesn't work (a font with [serifs](https://en.wikipedia.org/wiki/Serif) is still used).
Setting `'fontFamily' => 'Inter',` (v1.1.0) in the config file doesn't change anything.

Anyway, it looks like the cause must be somewhere else. Since the doc in the config file says ...
```
    /**
     * Global config for the avatar's font-family
     *
     * @type ?string
     *
     * @default \Filament\Facades\Filament::getFontFamily()
     */
    'fontFamily' => null,
```
... I tried obtaining the default with tinker, and the default is already *Inter*:
```
$ php artisan tinker
Psy Shell v0.12.0 (PHP 8.3.1 — cli) by Justin Hileman
> \Filament\Facades\Filament::getFontFamily()
= "Inter"
```

**Comment by Voltra** [comment]
Do you have the Inter font available globally on your system? If you don't the problem comes from svg text rendering from within an image tag. In which case the avatar component override should help as it uses the svg directly

**Comment by wq9578** [comment]
The font is installed locally in order to avoid external requests:
```
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('admin')
            ->path('admin')
            ->login()
            ->font(
                'Inter',
                url: asset('fonts/inter/fonts.css'),
                provider: LocalFontProvider::class,  // Avoid external HTTP(S) requests
            )
            ->defaultAvatarProvider(SvgAvatarsProviders::class)  // Avoid external HTTP(S) requests
            [...]
```

**Comment by Voltra** [comment]
Right, but you don't have the font installed on your PC's font repo?

**Comment by wq9578** [comment]
As specified by the above line `url: asset('fonts/inter/fonts.css'),`, the font is available in the public directory (log below).

The browser is loading the font correctly, and replacing `fonts/inter/fonts.css` with an invalid path (e.g., `fonts/inter2/fonts.css` causes an error in the browser console.

```
$ ls public/fonts/inter/fonts.css public/fonts/inter/inter-*
public/fonts/inter/fonts.css                            public/fonts/inter/inter-greek-ext-600-normal.woff
public/fonts/inter/inter-cyrillic-400-normal.woff       public/fonts/inter/inter-greek-ext-600-normal.woff2
public/fonts/inter/inter-cyrillic-400-normal.woff2      public/fonts/inter/inter-greek-ext-700-normal.woff
public/fonts/inter/inter-cyrillic-500-normal.woff       public/fonts/inter/inter-greek-ext-700-normal.woff2
public/fonts/inter/inter-cyrillic-500-normal.woff2      public/fonts/inter/inter-latin-400-normal.woff
public/fonts/inter/inter-cyrillic-600-normal.woff       public/fonts/inter/inter-latin-400-normal.woff2
public/fonts/inter/inter-cyrillic-600-normal.woff2      public/fonts/inter/inter-latin-500-normal.woff
public/fonts/inter/inter-cyrillic-700-normal.woff       public/fonts/inter/inter-latin-500-normal.woff2
public/fonts/inter/inter-cyrillic-700-normal.woff2      public/fonts/inter/inter-latin-600-normal.woff
public/fonts/inter/inter-cyrillic-ext-400-normal.woff   public/fonts/inter/inter-latin-600-normal.woff2
public/fonts/inter/inter-cyrillic-ext-400-normal.woff2  public/fonts/inter/inter-latin-700-normal.woff
public/fonts/inter/inter-cyrillic-ext-500-normal.woff   public/fonts/inter/inter-latin-700-normal.woff2
public/fonts/inter/inter-cyrillic-ext-500-normal.woff2  public/fonts/inter/inter-latin-ext-400-normal.woff
public/fonts/inter/inter-cyrillic-ext-600-normal.woff   public/fonts/inter/inter-latin-ext-400-normal.woff2
public/fonts/inter/inter-cyrillic-ext-600-normal.woff2  public/fonts/inter/inter-latin-ext-500-normal.woff
public/fonts/inter/inter-cyrillic-ext-700-normal.woff   public/fonts/inter/inter-latin-ext-500-normal.woff2
public/fonts/inter/inter-cyrillic-ext-700-normal.woff2  public/fonts/inter/inter-latin-ext-600-normal.woff
public/fonts/inter/inter-greek-400-normal.woff          public/fonts/inter/inter-latin-ext-600-normal.woff2
public/fonts/inter/inter-greek-400-normal.woff2         public/fonts/inter/inter-latin-ext-700-normal.woff
public/fonts/inter/inter-greek-500-normal.woff          public/fonts/inter/inter-latin-ext-700-normal.woff2
public/fonts/inter/inter-greek-500-normal.woff2         public/fonts/inter/inter-vietnamese-400-normal.woff
public/fonts/inter/inter-greek-600-normal.woff          public/fonts/inter/inter-vietnamese-400-normal.woff2
public/fonts/inter/inter-greek-600-normal.woff2         public/fonts/inter/inter-vietnamese-500-normal.woff
public/fonts/inter/inter-greek-700-normal.woff          public/fonts/inter/inter-vietnamese-500-normal.woff2
public/fonts/inter/inter-greek-700-normal.woff2         public/fonts/inter/inter-vietnamese-600-normal.woff
public/fonts/inter/inter-greek-ext-400-normal.woff      public/fonts/inter/inter-vietnamese-600-normal.woff2
public/fonts/inter/inter-greek-ext-400-normal.woff2     public/fonts/inter/inter-vietnamese-700-normal.woff
public/fonts/inter/inter-greek-ext-500-normal.woff      public/fonts/inter/inter-vietnamese-700-normal.woff2
public/fonts/inter/inter-greek-ext-500-normal.woff2
```

**Comment by Voltra** [comment]
Right, so as suspected some (if not all) browsers don't use fonts loaded on the websites to render SVGs, but only the ones on the already installed on the user's machine.

I suggest [this approach](https://github.com/Voltra/filament-svg-avatar?tab=readme-ov-file#replace-filaments-default-avatar-component) and I'll make the readme clearer about what each approach can do

**Comment by wq9578** [comment]
Creating a file `resources/views/vendor/filament-support/components/avatar.blade.php` with the content provided there doesn't fix the problem.

**Comment by Voltra** [comment]
It'd seem I need to adjust a few things, I'll do so ASAP for a v1.1.1

**Comment by Voltra** [comment]
With v1.2.0 this should be fixed, I'll be working on v1.2.1 to fix the proper text rendering

**Comment by Voltra** [comment]
Is this good on your end with the new instructions and file content?

**Comment by Voltra** [comment]
I'll assume this is fixed based on my testing, feel free to re-open if there's still an issue

**Comment by wq9578** [comment]
Upgraded to 1.2.2, but the problem still persists.

Any further steps required except upgrading?

**Comment by Voltra** [comment]
If the first approach (just the plugin, or just `SvgAvatarsProviders::class`) doesn't work, you have to try the second one.

As explained [in the README](https://github.com/Voltra/filament-svg-avatar?tab=readme-ov-file#replace-filaments-default-avatar-component):
* Create an override of filament's avatar component `resources/views/vendor/filament/components/avatar.blade.php`
* Fill it in with the provided code for the override
* Change the default avatar provider to `\Voltra\FilamentSvgAvatar\Filament\AvatarProviders\RawSvgAvatarProvider::class`

This should render an inline `<svg>` tag (with all the right attributes and styling) instead of an `<img/>` tag as filament does by default.

**Comment by Voltra** [comment]
In a future major version, I'll advise this as the default route. I'll probably look into making a stub for the override and place it where it needs to be.

**Comment by wq9578** [comment]
> If the first approach (just the plugin, or just `SvgAvatarsProviders::class`) doesn't work, you have to try the second one.
> 
> As explained [in the README](https://github.com/Voltra/filament-svg-avatar?tab=readme-ov-file#replace-filaments-default-avatar-component):
> 
> * Create an override of filament's avatar component `resources/views/vendor/filament/components/avatar.blade.php`
> * Fill it in with the provided code for the override
> * Change the default avatar provider to `\Voltra\FilamentSvgAvatar\Filament\AvatarProviders\RawSvgAvatarProvider::class`
> 
> This should render an inline `<svg>` tag (with all the right attributes and styling) instead of an `<img/>` tag as filament does by default.

This results in the error
```
syntax error, unexpected token "endif", expecting end of file
```

with reference to the following line: `resources/views/vendor/filament-svg-avatar/components/avatar-override.blade.php:16`

**Comment by Voltra** [comment]
`resources/views/vendor/filament-svg-avatar/components/avatar-override.blade.php` is an override of `vendor/voltra/filament-svg-avatar/resources/views/components/avatar-override.blade.php`. Is it up-to-date with the current version of the file?

Maybe it's a residual of a previous version and isn't needed anymore.

**Comment by wq9578** [comment]
```
$ diff resources/views/vendor/filament-svg-avatar/components/avatar-override.blade.php vendor/voltra/filament-svg-avatar/resources/views/components/avatar-override.blade.php 
7,11c7,8
< /**
<  * @var \Voltra\FilamentSvgAvatar\Contracts\SvgAvatarServiceContract $service
<  */
< $service = resolve(\Voltra\FilamentSvgAvatar\Contracts\SvgAvatarServiceContract::class);
< $initials = $attributes->has('alt') ? $service->getInitials($attributes->get('alt')) : null;
---
> $initials = $attributes->has('alt') ? \Voltra\FilamentSvgAvatar\Services\Utils::initials($attributes->get('alt')) : '';
> $initials = $initials ?: ($attributes->has('src') ? $attributes->get('src') : '');
15,29c12,23
<     :initials="$attributes->get('alt')"
<     {{
<         $attributes
<             ->class([
<                 'fi-avatar object-cover object-center',
<                 'rounded-md' => ! $circular,
<                 'fi-circular rounded-full' => $circular,
<                 match ($size) {
<                     'sm' => 'h-6 w-6',
<                     'md' => 'h-8 w-8',
<                     'lg' => 'h-10 w-10',
<                     default => $size,
<                 },
<             ])
<     }}
---
>     :attributes="$attributes->class([
>         'fi-avatar object-cover object-center',
>         'rounded-md' => ! $circular,
>         'fi-circular rounded-full' => $circular,
>         match ($size) {
>             'sm' => 'h-6 w-6',
>             'md' => 'h-8 w-8',
>             'lg' => 'h-10 w-10',
>             default => $size,
>         },
>     ])"
>     :initials="$initials"
```

**Comment by wq9578** [comment]
After copying the file with `cp vendor/voltra/filament-svg-avatar/resources/views/components/avatar-override.blade.php resources/views/vendor/filament-svg-avatar/components/avatar-override.blade.php` the error disappears, but instead of an image a question mark is shown:
![Question mark](https://github.com/Voltra/filament-svg-avatar/assets/121522862/28f5098b-c119-4df7-b4c9-9f8936208926)

The link to the (missing) image is `http://127.0.0.1:8000/user/SC` (shown by "open image in new tab").

**Comment by Voltra** [comment]
Are you missing the override of filament's avatar component?

**Comment by wq9578** [comment]
Of course I also had updated the PanelProvider:
`            ->defaultAvatarProvider(RawSvgAvatarProvider::class)`

**Comment by Voltra** [comment]
That is strange, because it outputs an inline `<svg>` not an `<img/>`

**Comment by Voltra** [comment]
Can you check if a bugfix from v1.2.3 fixes the issue and properly renders an SVG?

Due to how filament registers plugins, if you're using it, you might have the user-declared avatar provider get overridden unintentionally (due to how the package used to function).

Which means that `$panel->plugin(FilamentSvgAvatarPlugin::make())->defaultAvatarProvider(RawSvgAvatarProvider::class)` would work, where `$panel->defaultAvatarProvider(RawSvgAvatarProvider::class)->plugin(FilamentSvgAvatarPlugin::make())` would use the default SVG provider instead of `RawSvgAvatarProvider`.

**Comment by wq9578** [comment]
I have removed the file `resources/views/vendor/filament-svg-avatar/components/avatar-override.blade.php`, updated to the current version 1.2.4 with `composer update voltra/filament-svg-avatar`, and changed the line in the panel to `->defaultAvatarProvider(RawSvgAvatarProvider::class)`, but the question mark appears again.
Adding `->plugin(FilamentSvgAvatarPlugin::make())` doesn't help.

**Comment by Voltra** [comment]
The plugin is for per-instance customization, it shouldn't change the behavior if you weren't using it before and you don't have to use it.

When you inspect the generated code for the avatar, do you see something that looks like this:

```html
<svg width="500px" height="500px" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="fi-avatar object-cover object-center fi-circular rounded-full h-10 w-10 fi-user-avatar" src="A" alt="filament-panels::layout.avatar.alt">
    <rect x="0" y="0" width="500" height="500" rx="0" style="fill:rgb(0,135,179);"></rect>
    <text x="50%" y="50%" dy=".1em" fill="#ffffff" text-anchor="middle" dominant-baseline="middle" style="font-family: inherit; font-size: 250px; line-height: 1;">
        A
    </text>
</svg>
```

or do you see an `<img/>` tag?

There shouldn't be any `<img/>` tag for avatars with this setup.

Maybe something else is hooking into it? Maybe it's just a `php artisan optimize:clear` away?

**Comment by wq9578** [comment]
When saving the avatar image to disk, the file is:
```
<svg width="500px" height="500px" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg"><rect x="0" y="0" width="500" height="500" rx="0" style="fill:rgb(245,158,11);"/><text x="50%" y="50%" dy=".1em" fill="#000000" text-anchor="middle" dominant-baseline="middle" style="font-family: Inter; font-size: 250px; line-height: 1;">SC</text></svg>
```

Executing `php artisan optimize:clear` doesn't help.

**Comment by Voltra** [comment]
So it is an `<img/>` tag that is rendered

**Comment by wq9578** [comment]
> So it is an `<img/>` tag that is rendered

The SVG image is base64 encoded within an `<img>` tag being part of the HTML source of the page, it seems:

```
<div x-on:click="toggle" class="fi-dropdown-trigger flex cursor-pointer">
        <button aria-label="User menu" type="button" class="shrink-0">
            <img class="fi-avatar object-cover object-center fi-circular rounded-full h-8 w-8 fi-user-avatar" src="data:image/svg+xml;base64,PHN2ZyB3aWR0[...]4dD48L3N2Zz4=">
        </button>
    </div>
```

**Comment by Voltra** [comment]
That is the problem. This tells me the filament avatar component override isn't used.

I have a project I use the package on.

In my panel provider, I only have `->defaultAvatarProvider(RawSvgAvatarProvider::class)` (no plugin used).

I have the following content in `resources/views/vendor/filament/components/avatar.blade.php` (as per instructed in the README):

```php
<!-- resources/views/vendor/filament/components/avatar.blade.php -->

@props([
    'circular' => true,
    'size' => 'md',
])

<x-filament-svg-avatar::avatar-override
    :attributes="$attributes"
    :circular="$circular"
    :size="$size"
></x-filament-svg-avatar::avatar-override>
```

With this setup it does render an SVG as expected by using this approach.

**Comment by wq9578** [comment]
Some progress: Now the correct font seems to be used, but the logo is totally oversized (nearly half of the window/viewport), and a rectangle instead of a circle is displayed:

```
<svg width="500px" height="500px" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg">
    <rect x="0" y="0" width="500" height="500" rx="0" style="fill:rgb(245,158,11);"></rect>
    <text x="50%" y="50%" dy=".1em" fill="#000000" text-anchor="middle" dominant-baseline="middle" style="font-family: inherit; font-size: 250px; line-height: 1;">
        SC
    </text>
</svg>
```

Also the other avatars (dashboard, user select in multi-tenancy mode) are too large.

**Comment by Voltra** [comment]
That's curious, it should render properly and with the tailwind classes

**Comment by Voltra** [comment]
With the setup explained above, I get:

```html
<svg width="500px" height="500px" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="fi-avatar object-cover object-center fi-circular rounded-full h-8 w-8 fi-user-avatar" src="A" alt="filament-panels::layout.avatar.alt">
    <rect x="0" y="0" width="500" height="500" rx="0" style="fill:rgb(0,135,179);"></rect>
    <text x="50%" y="50%" dy=".1em" fill="#ffffff" text-anchor="middle" dominant-baseline="middle" style="font-family: inherit; font-size: 250px; line-height: 1;">
        A
    </text>
</svg>
```

**Comment by wq9578** [comment]
At the very first glance, a width/height of 500px and font-size of 250px seems very large.

**Comment by Voltra** [comment]
It would if it were a non-vector image. It is the default size and can be overridden using the plugin's config methods, or simply using the config file that can be published. The default size could change, but again it doesn't really matter since it'll be dynamically adjusted by the SVG rendering engine.

**Comment by wq9578** [comment]
When I manually change to `<svg width="50px" height="50px"` in the browser, the size is correct (but displaying a square, not a circle).

**Comment by Voltra** [comment]
Something is happening in your codebase that prevents the component from properly inheriting/applying the attributes

**Comment by wq9578** [comment]
Indeed, with a fresh installation, font, size, and shape (circle) are displayed correctly.
However, the initials "AO" instead of the expected "TU" (for Test User) are used.
This still has to be fixed.
Installation script, modified panel (with diff), and the blade are attached.

Resulting HTML source is:
```
<button aria-label="User menu" type="button" class="shrink-0">
            <!-- resources/views/vendor/filament/components/avatar.blade.php -->


<svg width="500px" height="500px" viewBox="0 0 500 500" xmlns="http://www.w3.org/2000/svg" class="fi-avatar object-cover object-center fi-circular rounded-full h-8 w-8 fi-user-avatar">
    <rect x="0" y="0" width="500" height="500" rx="0" style="fill:rgb(245,158,11);"></rect>
    <text x="50%" y="50%" dy=".1em" fill="#000000" text-anchor="middle" dominant-baseline="middle" style="font-family: inherit; font-size: 250px; line-height: 1;">
        AO
    </text>
</svg>
        </button>
```

Screenshot:
<img width="1219" alt="Screenshot" src="https://github.com/Voltra/filament-svg-avatar/assets/121522862/bd80331e-f9e0-4003-a275-4a2939a738c0">

Looks like I have to re-build my app from scratch step by step and check if and when the size and shape problem pops up again.
Maybe there is a conflict with some other package.


(Attachments)

avatar_test.sh:
```
#!/bin/sh -e

echo "Reproducing https://github.com/Voltra/filament-svg-avatar/issues/1#issuecomment-2038070726"

# Laravel
composer create-project laravel/laravel avatar_test

cd avatar_test

# Filament
composer require filament/filament:"^3.2" -W
php artisan filament:install --panels
php artisan make:filament-user --name="Test User" --email=user@example.com --password=password

# Avatar plugin
composer require voltra/filament-svg-avatar
php artisan vendor:publish --tag="filament-svg-avatar-config"
php artisan vendor:publish --tag="filament-svg-avatar-views"

# Avatar plugin: config
mv app/Providers/Filament/AdminPanelProvider.php app/Providers/Filament/AdminPanelProvider.php.org
cp -p ../AdminPanelProvider.php app/Providers/Filament/
# Show difference, expect false (some difference)
! diff app/Providers/Filament/AdminPanelProvider.php.org app/Providers/Filament/AdminPanelProvider.php > ../diff.log

# Avatar plugin: blade
mkdir -p resources/views/vendor/filament/components
cp -p ../avatar.blade.php resources/views/vendor/filament/components/

echo "Now open http://127.0.0.1:8000/admin"
```

avatar.blade.php (as above):
```
<!-- resources/views/vendor/filament/components/avatar.blade.php -->

@props([
    'circular' => true,
    'size' => 'md',
])

<x-filament-svg-avatar::avatar-override
    :attributes="$attributes"
    :circular="$circular"
    :size="$size"
></x-filament-svg-avatar::avatar-override>
```

AdminPanelProvider.php:
```
<?php

namespace App\Providers\Filament;

use Filament\Http\Middleware\Authenticate;
use Filament\Http\Middleware\DisableBladeIconComponents;
use Filament\Http\Middleware\DispatchServingFilamentEvent;
use Filament\Pages;
use Filament\Panel;
use Filament\PanelProvider;
use Filament\Support\Colors\Color;
use Filament\Widgets;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\AuthenticateSession;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\View\Middleware\ShareErrorsFromSession;
use Voltra\FilamentSvgAvatar\Filament\AvatarProviders\RawSvgAvatarProvider;

class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->login()
            ->colors([
                'primary' => Color::Amber,
            ])
            ->discoverResources(in: app_path('Filament/Resources'), for: 'App\\Filament\\Resources')
            ->discoverPages(in: app_path('Filament/Pages'), for: 'App\\Filament\\Pages')
            ->pages([
                Pages\Dashboard::class,
            ])
            ->discoverWidgets(in: app_path('Filament/Widgets'), for: 'App\\Filament\\Widgets')
            ->widgets([
                Widgets\AccountWidget::class,
                Widgets\FilamentInfoWidget::class,
            ])
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
            ])
            ->authMiddleware([
                Authenticate::class,
            ])
            ->defaultAvatarProvider(RawSvgAvatarProvider::class);
    }
}
```

diff.log:
```
19a20
> use Voltra\FilamentSvgAvatar\Filament\AvatarProviders\RawSvgAvatarProvider;
56c57,58
<             ]);
---
>             ])
>             ->defaultAvatarProvider(RawSvgAvatarProvider::class);
```

**Comment by Voltra** [comment]
Would `AO` be the result of the initials of a translation for `filament-panels::layout.avatar.alt` ?

**Comment by Voltra** [comment]
With v1.2.6, translations of filament's default avatar alt text should be gone

**Comment by wq9578** [comment]
I'm re-building my app from scratch, and the layout problem seems to be gone.
But it incorrectly uses the initials "AO" again (v1.2.6).

**Comment by wq9578** [comment]
Maybe `$user` is not set (is null) when this function is being called:

```
    public function getInitials(Model|Authenticatable $user): string
    {
        return Utils::initials(Filament::getNameForDefaultAvatar($user));
    }
```
https://github.com/Voltra/filament-svg-avatar/blob/0455ff7fa0000de9e52ebb3c1a9f12c56ac242e1/src/Services/FilamentSvgAvatarService.php#L53

For example:
1. https://github.com/filamentphp/filament/discussions/4390
2. https://github.com/filamentphp/filament/issues/4398

**Comment by Voltra** [comment]
Hmm I doubt that would be the issue, that's the signature from the interface

**Comment by Voltra** [comment]
Do you have a translation for `filament-panels::layout.avatar.alt` ?

**Comment by Voltra** [comment]
Or maybe your tenant model has a `name` attribute (and doesn't implement filament's `HasName`) that conflicts with filament's default name resolution

https://github.com/filamentphp/filament/blob/60afe878a45d45997d4d2fb33f60ef7e94f17337/packages/panels/src/FilamentManager.php#L395

**Comment by wq9578** [comment]
> Do you have a translation for `filament-panels::layout.avatar.alt` ?

No, and even with locale 'en' explicitly set it remains "AO".

**Comment by wq9578** [comment]
> Or maybe your tenant model has a `name` attribute (and doesn't implement filament's `HasName`) that conflicts with filament's default name resolution
> 
> https://github.com/filamentphp/filament/blob/60afe878a45d45997d4d2fb33f60ef7e94f17337/packages/panels/src/FilamentManager.php#L395

That doesn't seem to be the problem.

Implementing some widget shows the correct user, team, and initials:
```
use App\Models\Team;
use App\Models\User;
use Filament\Facades\Filament;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;
use Voltra\FilamentSvgAvatar\Services\Utils;

class UserDisplay extends BaseWidget
{
    protected function getStats(): array
    {
        return [
            Stat::make('User', ($user = User::current())->name),
            Stat::make('Team', ($team = Team::current())->name ?? '(none)'),
            Stat::make('Initials', Utils::initials(Filament::getNameForDefaultAvatar($user))),
        ];
    }
}
```

If I then implement `HasName` in both `User` and `Team`, the widget correctly displays "TU" for ("Test User"), but the avatar still displays "AO":
```
    public function getFilamentName(): string
    {
        return "Test User";
    }
}
```

**Comment by Voltra** [comment]
That's very odd, I have no idea what could cause it to render `AO`, especially everytime.

Could you please dd the results of `$attributes->get('src')` and `$attributes->get('alt')` in the override template?

`src` should be `TU`, and I'm wondering if something somewhere doesn't override `alt` to `AO`

**Comment by wq9578** [comment]
Adding `{!! dd($attributes->get('src'), $attributes->get('alt')) !!}` to `resources/views/vendor/filament/components/avatar.blade.php` yields:

```
"TU" // resources/views/vendor/filament/components/avatar.blade.php
"Avatar of Test User" // resources/views/vendor/filament/components/avatar.blade.php
```

Obviously "Avatar of" => "AO" :)

**Comment by Voltra** [comment]
So there was a translation somewhere, interesting. Seems parameterized, so I'll adjust the template. I probably had the translations published, hence why it didn't pick it up on my side.

**Comment by wq9578** [comment]
> So there was a translation somewhere, interesting. Seems parameterized, so I'll adjust the template

The search string `Avatar of` occurs only once in the source tree, in `vendor/filament/filament/resources/lang/en/layout.php`:
```
    'avatar' => [
        'alt' => 'Avatar of :name',
    ],
```

**Comment by Voltra** [comment]
Should be fixed in v1.2.7. I dropped the use of `alt` since I couldn't reasonably determine if it were generated from the default translation string.

**Comment by wq9578** [comment]
Still displaying "AO" (v1.2.7) ...

**Comment by Voltra** [comment]
Not possible, I've removed any trace of `alt` from `<x-filament-svg-avatar::avatar-override/>` so that you don't even need to edit the core filament override.

Possibly a `cache:clear` or an `optimize:clear` can do the trick.

**Comment by wq9578** [comment]
`php artisan cache:clear && php artisan optimize:clear` doesn't help.

Oddly, with `$panel->defaultAvatarProvider(SvgAvatarsProviders::class)` behaviour changes depending on whether `resources/views/vendor/filament/components/avatar.blade.php` exists.
With blade: `$attributes->get('src')` returns `data:image/svg+xml;base64,[...]`.
Without blade: Correct initials, but serifs are used again.

**Comment by Voltra** [comment]
That is "expected". The override of filament's core avatar component is specifically made for the `RawSvgAvatarProvider` which behaves completely differently than other avatar providers (for the sake of rendering a correct SVG whilst using Filament's whole avatar system).

Now I'm extremely confused. The override in `resources/views/vendor/filament/components/avatar.blade.php` delegates to `<x-filament-svg-avatar::avatar-override/>` which doesn't use the `alt` attribute anymore.

**Comment by wq9578** [comment]
Excerpt from my file `resources/views/vendor/filament-svg-avatar/components/avatar-override.blade.php` (v1.2.7):

```
@php
    $filamentAvatarAltLangStr = 'filament-panels::layout.avatar.alt';
    $initials = $attributes->has('alt') ? $attributes->get('alt') : '';

    $unwantedLabels = [$filamentAvatarAltLangStr, __($filamentAvatarAltLangStr)];

    $initials = in_array($initials, $unwantedLabels)
        ? ''
        : \Voltra\FilamentSvgAvatar\Services\Utils::initials($initials);

    $initials = $initials ?: ($attributes->has('src') ? $attributes->get('src') : '');
@endphp
```

**Comment by Voltra** [comment]
Oh... well that's on me. I should have put that somewhere else. You may delete it and re-publish the override using

```bash
php artisan vendor:publish --tag=filament-svg-avatar-core-overrides
```

**Comment by wq9578** [comment]
Now the text tag contains a base64 encoded string again:
```
<text x="50%" y="50%" dy=".1em" fill="#000000" text-anchor="middle" dominant-baseline="middle" style="font-family: inherit; font-size: 250px; line-height: 1;">
        data:image/svg+xml;base64,[...]
    </text>
```
The displayed characters "4LD" are from the center of the base64 encoded string.

**Comment by Voltra** [comment]
I believe you're not using `RawSvgAvatarProvider`

**Comment by wq9578** [comment]
You are right. Now it works.
Thanks a lot!!!
