### ISSUE TITLE
Laravel 11 Support

### ISSUE THREAD

**Issue by wq9578** [Voltra/filament-svg-avatar#2]
### What happened?

Update to Laravel 11 is impossible without removing the package first.

### How to reproduce the bug

https://laravel.com/docs/11.x/upgrade

### Package Version

1.0

### PHP Version

8.3.1

### Laravel Version

11.1.1

### Which operating systems does with happen with?

macOS

### Notes

Package requires illuminate/contracts which is replaced in Laravel 11.

Log:
```
    - Only one of these can be installed: illuminate/contracts[v5.5.0, ..., v5.8.36, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0-beta.1, ..., v9.52.16, v10.0.0, ..., v10.48.4, v11.0.0, ..., v11.1.1], laravel/framework[v11.0.0, ..., v11.1.1]. laravel/framework replaces illuminate/contracts and thus cannot coexist with it.
    - voltra/filament-svg-avatar[1.0.0, ..., 1.2.1] require illuminate/contracts ^10.0 -> satisfiable by illuminate/contracts[v10.0.0, ..., v10.48.4].
```

**Comment by Voltra** [comment]
Noted! Will provide a minor version update that includes support ASAP

**Comment by Voltra** [comment]
[v1.2.2](https://github.com/Voltra/filament-svg-avatar/releases/tag/v1.2.2) should fix this. Please tell me if something's wrong or if it fixes it

**Comment by wq9578** [comment]
Fixed. Thanks a lot!

But https://github.com/Voltra/filament-svg-avatar/issues/1 is still open.
